

//GET
export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRIES_BY_NAME = "GET_COUNTRIES_BY_NAME"
export const GET_COUNTRIES_BY_ID = "GET_COUNTRIES_BY_ID"
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const GET_ACTIVITIES_BY_NAME = "GET_ACTIVITIES_BY_NAME"
export const GET_ACTIVITIES_BY_ID = "GET_ACTIVITIES_BY_ID"
//POST
export const POST_ACTIVITY = "POST_ACTIVITY"

//FILTROS
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY"

//ORDEN
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION"

//FAIL
export const FAIL = "FAIL"
